heartbeat.heartbeat_type.*:
  type: config_entity
  label: 'Heartbeat type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    hid:
      type: serial
      label: 'hid'
    message_id:
      type: string
      label: 'message_id'
    description:
      type: string
      label: 'description'
    mainentity:
      type: string
      label: 'Main Entity'
    message:
      type: string
      label: 'message'
    message_concat:
      type: string
      label: 'message_concat'
    perms:
      type: integer
      label: 'perms'
    group_type:
      type: string
      label: 'group_type'
    arguments:
      type: blob
      label: 'arguments'
    variables:
      type: blob
      label: 'variables'
    attachments:
      type: blob
      label: 'attachments'
heartbeat.friendship.*:
  type: config_entity
  label: 'Heartbeat Friendship config'
  mapping:
    id:
      type: string
      label: 'ID'
    uid:
      type: integer
      label: 'uid'
    uid_target:
      type: integer
      label: 'uid_target'
    status:
      type: integer
      label: 'status'
    created:
      type: integer
      label: 'Created timestamp'
