<?php

/**
 * @file
 * Contains kek_custom.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kek_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kek_custom module.
    case 'help.page.kek_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modifications to Kekistan') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_alter().
 */
function kek_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id == 'search_block_form') {
    $form['keys']['#attributes']['placeholder'] = t('Search Kekistan');
  }

}
